### ISSUE TITLE
Aș folosi un guard (guardValidCnp) și la prima eroare aș face throw

### ISSUE THREAD

**Issue by adrian7** [mmlTools/CNPDecoder#3]
https://github.com/mmlTools/CNPDecoder/blob/c2ce6bb481114071b242e4d655b59eec0d7b19da/CNPDecoder.php#L40

**Comment by mmlTools** [comment]
Am compactat cele doua metode de validare și spargere într-o singură metodă de validare.
Am implementat o clasă de excepții pentru a putea citi mai ușor erorile.
Am transofrmat contantele definite în constante locale.

Actualizare demo: 705a4aa46159f1b66d5e37f45994645ea05eaa94
Actualizare clasă: bc1b7e117c647b7bdc41a40c25bfd50e0ed6fc4c

Referință către issue nr.  #2
